apiVersion: apps/v1
kind: Deployment
metadata:
  name: assur-front
  namespace: preprod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assur-front
  template:
    metadata:
      labels:
        app: assur-front
    spec:
      serviceAccountName: internal-app
      containers:
      - name: assur-front
        image: maryeeem/assur-front:4.0.5
        command: ['sh', '-c', 'npm run dev']
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3000"
        - name: NEXT_PUBLIC_API_URL
          value: "http://assureapi.local.com/api"
        - name: BACK_URL
          value: "http://assureapi.local.com/api"
        - name: FRONT_URI
          value: "http://localhost:3001"
        - name: secret
          value: "a'NrkZi22NIo.QZnxa!a?"
        volumeMounts:
        - name: secrets-store
          mountPath: "/mnt/secrets-store"
          readOnly: true
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
      volumes:
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: vault-assure-api-provider
