# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: assur-front-ingress
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: "/" 
#     nginx.ingress.kubernetes.io/ssl-redirect: "true"
#     nginx.ingress.kubernetes.io/ssl-passthrough: "true"
# spec:
#   ingressClassName: nginx
#   rules:
#   - host: assurefront.local.com  # Replace with your domain
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: assur-front-service
#             port:
#               number: 3001
#   tls:
#   - hosts:
#     - assurefront.local.com
#     secretName: assurefront-tls
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: assur-front-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/" 
    nginx.ingress.kubernetes.io/ssl-redirect: "false"  # Disable automatic redirection to HTTPS
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
  - host: assurefront.local.com  # Replace with your domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: assur-front-service
            port:
              number: 3001
